site_name: PyOkra
site_description: A developer friendly wrapper for Okra API
site_url: https://github.com/

theme:
  name: "material"
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: light green
      accent: green
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: light green
      accent: green
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
  features:
    - search.suggest
    - search.highlight
    - content.tabs.link
  icon:
    repo: fontawesome/brands/github-alt
  logo: img/icon-white.svg
  favicon: img/favicon.png
  language: en
repo_name: gray-adeyi/pyokra
repo_url: https://github.com/gray-adeyi/pyokra
edit_uri: ''

plugins:
  - search
  - mkdocstrings

nav:
  - Introduction: index.md
  - tutorials.md
  - How-To Guides: how-to-guides.md
  - Reference:
    - "reference/index.md"
    - "reference/utils.md"
  - explanation.md
